server:
  port: 8181
spring:
  application:
    name: fraud-check
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  profiles:
    active: default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true